### ISSUE TITLE
C# demos fail at createSessionControl()

### ISSUE THREAD

**Issue by Ciders** [Xirexel/CaptureManager-SDK-Demos#1]
Great work on the SDK! Many coffees are in your future.
Some of the C# demos fail to function properly for me. (e.g. WPFRtspServer, WPFStreamer)  
They error out at the same line. 

```
var lSessionControl = mCaptureManager.createSessionControl();
if (lSessionControl == null)
         return;
```

Am I missing something?

**Comment by Xirexel** [comment]
What error message content?

**Comment by Ciders** [comment]
System.NullReferenceException: 'Object reference not set to an instance of an object.'
No exception data, no stack trace.
```
var lSessionControl = mCaptureManager.createSessionControl();
if (lSessionControl == null)
         return;    //  <--- error thrown here. stange.
```
Perhaps it is my windows or project configurations?

**Comment by Xirexel** [comment]
So, error cannot be thrown in return. Check **mCaptureManager** - it can be null, and **mCaptureManager.createSessionControl()** generate **System.NullReferenceException**.

**Comment by Ciders** [comment]
**mCaptureManager** is not null.
I have added a reference to **CaptureManagerToCSharpProxy** instead of the nuget to help dig into this. **CaptureManagerToCSharpProxy** depends on  **CaptureManagerLibrary**. Where can i find  **CaptureManagerLibrary**?

**Comment by Xirexel** [comment]
**CaptureManagerLibrary** is exported from CaptureManager.dll after registration COM object: **regsvr32.exe .\CaptureManager.dll**

**Comment by Ciders** [comment]
ah, ok.  

I installed the demos repository onto a different computer and all works.  Classic.

Thanks again for the SDK! I cant wait to fully dig into it.

Feel free to delete this thread.

**Comment by Ciders** [comment]
Ok, amateur hour continues. Debug **Just my Code** was disabled, accounting for the error at **lSessionControl**. Once I enable debug Just my Code it now debugs as expected. 
However mISession is null and returns. Any inkling why mISession could be null?

```
var lSessionControl = mCaptureManager.createSessionControl();
if (lSessionControl == null)
     return;

mISession = lSessionControl.createSession(lSourceMediaNodeList.ToArray());
if (mISession == null)
      return;  //   <---- returns here
```

**Comment by Xirexel** [comment]
What demo project do you test? **lSourceMediaNodeList** is a list of sources for capturing - if **createSession** cannot create correct topology from source to sink then it returns the null ISession object.
