### ISSUE TITLE
How to output webcam preview directly to WPF control?

### ISSUE THREAD

**Issue by geocine** [Xirexel/CaptureManager-SDK-Demos#5]
> I am interested on the [WPFWebViewerEVRAsync](https://github.com/Xirexel/CaptureManager-SDK-Demos/tree/master/CSharpDemos/WPFWebViewerEVRAsync) however I prefer not to use a `WindowsFormsHost`. Is there a way to directly output the video stream to a WPF control?
> 
> I tried to replace it with the `VideoPanel` class that I found on other demo but its slower than the `WindowsFormsHost` version.

Reposting here for visibility, originally posted at https://github.com/Xirexel/CaptureManagerSDK/issues/11

**Comment by Xirexel** [comment]
Hi,
I can recommend [WPFViewerEVRDisplay](https://github.com/Xirexel/CaptureManager-SDK-Demos/tree/master/CSharpDemos/WPFViewerEVRDisplay) - this code demonstrates using DirectX9 texture as video rendering target.
